### ISSUE TITLE
Checklist of all the things

### ISSUE THREAD

**Issue by mvasilkov** [mvasilkov/neatness2022#1]
- [ ] PriorityQueue.ts
    - [ ] Fix all errors
    - [ ] Use `delete` on array, instead of setting to `null`
    - [ ] Add header comment
